### ISSUE TITLE
Hide Internal FuncX Routes From Internet

### ISSUE THREAD

**Issue by BenGalewsky** [funcx-faas/funcx-container-service#36]
# Problem
Microservices in funcX may need to communicate with the funcX app, however they do not have any credentials to access the endpoints.

# Approach
Make these REST endpoints free from any auth checks and only allow access from inside the Kubernetes cluster.

Update the Ingres to add a `/v2/internal` route.

```yaml
      - path: /v2/internal
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app.ingress.defaultBackend }}
            port: 
              number: 80
```

This causes any attempts to reach these endpoints to route users to an error page.

Update the app and the container service to use this new route
